api/urls.py
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.urls import path, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'commodities', CommodityAPIView, 'Commodity')
router.register(r'simulations', SimulationAPIView, 'Simulation')
router.register(r'stocks', StockAPIView, 'Stock')
router.register(r'industries', IndustryAPIView, 'Industry')
router.register(r'classes', SocialClassAPIView, 'Social Class')
router.register(r'owners', OwnerAPIView, 'Owner')
router.register(r'trace', TraceAPIView, 'Trace')

urlpatterns = [
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    # path('api/commodities/',CommodityListAPIView.as_view(), name='Commodities'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),    # API Schema:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),    # Optional UI:
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),     # Optional UI:
    path('hello/', HelloView.as_view(), name='hello'),    
    path("api/action/", BasicAPI.as_view()),
]

capitalism/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from api.views import BasicAPI

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('economy.urls')),
    path('', include('frontend.urls')),
    path('', include('api.urls')),
]

economy/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from economy import views
from economy import actions

urlpatterns = [
    path('simulations/',views.SimulationListView.as_view(), name='simulations'),
    path('user-dashboard/',views.userDashboard, name='user_dashboard'),
    path('initialize/', views.home,name='initialize'),
    path('create-simulation/', views.home, name='create-simulation'),
    path('create-simulation/<int:pk>', views.createSimulation, name='create-simulation'),
    path('select-simulation/<int:pk>', views.home, name='select-simulation'),
    path('delete-simulation/<int:pk>', views.home, name='delete-simulation'),
    path('restart-simulation/<int:pk>', views.home, name='restart-simulation'),
    path('',views.home),
    path('home/', views.home),
    path('demand/',actions.set_demand_and_supply),
    path('trade/', actions.trade),
    path('retrace/',actions.restart_trace),
    path('setup/',actions.setup),
    path('admin-reset/',actions.admin_reset, name='admin-reset'),
    path('vp', actions.set_commodities_from_stocks),
    path('produce',actions.produce),
    path('trace/',views.TraceListView.as_view()),
    path('commodities/', views.CommodityListView.as_view(),name='commodity-list'),
    path('stocks/',views.StockListView.as_view()),
    path('industries/',views.IndustryListView.as_view()),
    path('owners/',views.OwnerListView.as_view()),
    path('social_classes/',views.SocialClassListView.as_view()),
    path('buyers/',views.BuyerListView.as_view()),
    path('sellers/',views.SellerListView.as_view()),
    path("commodities/<pk>/", views.CommodityDetailView.as_view()),    
    path("social_classes/<pk>/", views.SocialClassDetailView.as_view()),    
    path("industries/<pk>/", views.IndustryDetailView.as_view()),    
    path("stocks/<pk>/", views.StockDetailView.as_view()),
    path("owners/<pk>/", views.OwnerDetailView.as_view()),
    path("economy/",views.economy_view),
    path('simulations/<pk>',views.SimulationDetailView.as_view(), name='simulation'),
]

economy/models.py
from django.db import models
import typing
import copy
from django.db.models import Q
from django.contrib.auth.models import User
# from accounts.models import User
# from capitalism.settings import AUTH_USER_MODEL
# from polymorphic.models import PolymorphicModel

Owner=typing.NewType("Owner",models.Model) # to allow forward reference in class 'Commodity'
Stock=typing.NewType("Stock",models.Model) # to allow forward reference in class 'Simulation'

class Simulation(models.Model):
    user=models.ForeignKey(User,default=None,null=True,on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    time_stamp=models.IntegerField(default=0)
    state=models.CharField(max_length=20, default="TEMPLATE") # Either TEMPLATE or ACTIVE
    periods_per_year=models.SmallIntegerField(default=1)
    population_growth_rate = models.FloatField(default=1)
    investment_ratio = models.FloatField(default=1)
    labour_supply_response = models.CharField(max_length=50, default="UNDEFINED")
    price_response_type = models.CharField(max_length=50, default="UNDEFINED")
    melt_response_type = models.CharField(max_length=50, null=True, blank=True,default=None)
    currency_symbol = models.CharField(max_length=2, default="$")
    quantity_symbol = models.CharField(max_length=2, default="#")
    melt=models.FloatField(null=False, blank=False,default=1)    

    class Meta:ordering = ['pk'] 
    def __str__(self):return f'{self.name}({str(self.pk)})'

    @property
    def link(self): return f'<a href = "/simulations/{self.id}">{self.name}</a>'    

    #Make a deep clone of myself and all associated objects
    def clone(self,user):
        print(f'The simulation {self.name} of type {self.state} and id {self.id} owned by {self.user} is cloning itself at the request of user {user}')
        report(self,1,f'cloning the simulation {self.name} with id {self.id} and owner {self.user}')
        old_id=self.id
# Pick up the children of this simulation before cloning the simulation itself
        new_commodities=Commodity.objects.filter(simulation=self) 
# Now clone the simulation so the new cloned objects can point to it
        self.state='ACTIVE'
        self.user=user
        self.time_stamp=self.time_stamp+1
        self.pk=None
        self.save()
        print(f'created new simulation {self.name} of type {self.state} owned by {self.user} with time stamp {self.time_stamp}')
        old_simulation=Simulation.objects.get(id=old_id)
        new_time_stamp=self.time_stamp
        print(f'old_self is now {old_simulation} and new_self is {self}')
# clone the commodities first
        for commodity in new_commodities:
            commodity.pk=None
            commodity.simulation=self
            commodity.time_stamp=new_time_stamp
            commodity.save()        
            print(f' Cloned commodity {commodity.name} for user {self.user}. ID is {commodity.pk} with time stamp {commodity.time_stamp}')
# Now clone the children recursively
        old_commodities=Commodity.objects.filter(simulation=old_simulation) # self has changed, so we have to rebuild this queryset
        print(f'new_commodities is now {new_commodities} and old_commodities is now {old_commodities}')
        for commodity in old_commodities:
            new_industries= Industry.objects.filter(commodity=commodity)
            new_social_classes=SocialClass.objects.filter(commodity=commodity)
            for industry in new_industries:
                new_stocks=Stock.objects.filter(owner=industry)
                new_industry=copy.deepcopy(industry)
                new_industry.pk=None
                new_industry.id=None
                new_industry.commodity=commodity 
                new_industry.simulation=self
                new_industry.time_stamp=new_time_stamp
                new_industry.save()                
                print(f'  Cloned industry {new_industry.name} for user {self.user}. ID is {new_industry.pk} and time stamp is {new_industry.time_stamp}')
                for stock in new_stocks:
                    new_stock=copy.deepcopy(stock)
                    new_stock.pk=None
                    new_stock.id=None
                    new_stock.time_stamp=new_time_stamp
                    new_stock.owner=new_industry
                    new_stock.simulation=self
                    new_stock.save()
                    # NOTE at this point we don't have the correct commodity object for the stock. 
                    # Instead, we have the commodity object of the old stock, which is one time_stamp behind
                    print(f'   Cloned stock of {new_stock.commodity.name} of type {new_stock.usage_type} for industry {industry.name} with old ID {stock.id} and new ID {new_stock.id}. time_stamp is {new_stock.time_stamp}' )
            for social_class in new_social_classes:
                new_stocks=Stock.objects.filter(owner=social_class)
                new_social_class=copy.deepcopy(social_class)
                new_social_class.pk=None
                new_social_class.id=None
                new_social_class.commodity=commodity
                new_social_class.simulation=self
                new_social_class.time_stamp=new_time_stamp
                new_social_class.save()                
                print(f'  Cloned social class {new_social_class.name} for user {self.user}. ID is {new_social_class.id} and time_stamp is {new_social_class.time_stamp}')
                for stock in new_stocks:
                   new_stock=copy.deepcopy(stock)
                   new_stock.pk=None
                   new_stock.id=None
                   new_stock.time_stamp=new_time_stamp
                   new_stock.owner=new_social_class
                   new_stock.simulation=self
                   new_stock.save() 
                   print(f'   Cloned stock of {new_stock.commodity.name} of type {new_stock.usage_type} for social class {social_class.name} with old ID {stock.id} new ID {new_stock.id} and time stamp {new_stock.time_stamp}')

# NOW revisit all the stocks and set their commodity properly
        for stock in Stock.objects.filter(time_stamp=new_time_stamp):
            old_commodity=stock.commodity # at this point, we haven't yet updated to the new commodity. We have to find it.
            print(f'looking for stock of commodity {old_commodity.name} for the stock called {stock.name}')
            print(f'we also want the time_stamp to be {new_time_stamp} and the simulation to be {stock.simulation}')
            new_commodity=Commodity.objects.get(simulation=self,name=old_commodity.name,time_stamp = new_time_stamp)
            stock.commodity=new_commodity
            stock.save()
            print(f'updated the commodity of the stock called {stock.name} and its time stamp was changed from {old_commodity.time_stamp} to {stock.commodity.time_stamp}')

        return
    
class Commodity(models.Model):
    name = models.CharField(max_length=255, default="UNDEFINED")
    simulation = models.ForeignKey(Simulation, related_name='commodities', default=None,on_delete=models.CASCADE)
    time_stamp=models.IntegerField(default=0)
    origin = models.CharField(max_length=255,default="UNDEFINED")
    usage = models.CharField(max_length=255, default="UNDEFINED")
    size = models.FloatField(default=0)
    total_value = models.FloatField(default=0)
    total_price = models.FloatField(default=0)
    unit_value = models.FloatField(default=1)
    unit_price = models.FloatField(default=1)
    turnover_time = models.FloatField(default=360)
    demand = models.FloatField(default=0)
    supply = models.FloatField(default=0)
    allocation_ratio = models.FloatField(default=1)
    display_order = models.IntegerField(null=True, default=1)
    image_name = models.CharField(max_length=255, default="UNDEFINED")
    tooltip = models.CharField(max_length=255, default="UNDEFINED")
    monetarily_effective_demand=models.FloatField(default=0)
    investment_proportion=models.FloatField(default=0)

    class Meta:
        verbose_name_plural = 'Commodities'   
        ordering = ['simulation','pk',] 

    def __str__(self):return f'{self.name}({str(self.pk)})'
    @property
    def link(self): return f'<a href = "/commodities/{self.id}">{self.name}</a>'

    def constrain_demand(self):
        report(self.simulation,2,f'Demand for {self.name} is {self.demand} and supply is {self.supply}')
        if self.supply==0:
            report(self.simulation,1,f"Zero Supply of {self.link}")
            self.alllocation_ratio=0
        else:
            self.allocation_ratio=self.demand/self.supply
        #we could do without allocation_ratio altogether but for the user to see what is going on, it is useful
        self.demand=self.demand*self.allocation_ratio
        self.save()
        report(self.simulation,2,f'Demand for {self.link} has been constrained by supply to {self.demand}')

class Owner(models.Model):
    name = models.CharField(max_length=255,default="UNDEFINED")
    # simulation = models.ForeignKey(Simulation, related_name='owners', on_delete=models.CASCADE)
    # simulation_number=models.IntegerField(default=1)
    commodity = models.ForeignKey(Commodity, null=True, related_name='producers',on_delete=models.CASCADE, default=None) # Many industries per commodity

    class Meta:
        ordering = ['pk'] 

    def __str__(self):return f'{self.name}({str(self.id)})'
    @property
    def link(self): return f'<a href = "/owners/{self.id}">{self.name}</a>'
    @property
    def sales_stock(self):return self.stocks.get(usage_type="Sales")
    @property
    def money_stock(self):
        # print(f'{self.name} is looking for his money stock')
        # candidates=Stock.objects.filter(owner=self,usage_type="Money")
        # print(f'candidates are {candidates}')
        return Stock.objects.get(owner=self,usage_type="Money")
    def productive_stocks(self):return self.stocks.filter(usage_type="Production")

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Capitalism 11.8</title>
    <meta name="description" content="Capitalism 11.6">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'w3.css' %}">    
    <link rel="script" type="text/css" href="{% static 'w3.js' %}">    
    <link rel="script" type="text/css" href="{% static 'bootstrap.bundle.min.js' %}">    
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome.css' %}">    
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap5.css' %}">    

    
    <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.css"> -->
    <!-- <link rel="shortcut icon" href="{% static '/img/faviconV2.png' %}"> -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    <!-- <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.js"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->

<!-- The following replaced by static files -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">     -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->

</head>

<body>
    {% include "navbar.html" %}
    <div class="w3-container">
             {% block content %}{% endblock %}
    </div>
</body>

</html>

templates/buyers.html
{% extends "base.html" %} {% block content %}
<h3 class="w3-center">Buyers</h3>
<table id="Buyers" class="w3-table-all w3-card w3-small">
    <thead>
        <tr>
            <th> buyer id </th>
            <th> simulation </th>
            <th> purchaser</th>
            <th> commodity</th>
            <th> demand </th>
            <th> stock </th>
            <!-- <th> money owner (check) </th> -->
            <th> money </th>

        </tr>
    </thead>
    <tbody>
        {% for buyer in buyer_list %}
        <tr>
            <td>{{ buyer.id}} </td>
            <td>{{ buyer.purchaseStock.simulation.id}} </td>
            <td>{{ buyer.purchaseStock.owner.name}} </td>
            <td>{{ buyer.purchaseStock.commodity.name}} </td>
            <td>{{ buyer.purchaseStock.demand}} </td>
            <td>{{ buyer.purchaseStock.size}} </td>
            <!-- <td>{{ buyer.moneyStock.owner.name}} </td> -->
            <td>{{ buyer.moneyStock.size}} </td>
        </tr>
        {% endfor %}



    </tbody>
</table>

{% endblock %} 

templates/create-simulation.html
{% extends "base.html" %} {% block content %}
<h3 class="w3-center">Projects</h3>
<table id="commodities" class="w3-table-all w3-card w3-small">
    <thead>
        <tr>
            <th>id</th>
            <th>User</th>
            <th>Name</th>
            <th>State</th>
        </tr>
    </thead>
    <tbody>
        {% for project in project_list %}
        <tr>
            <td> {{ project.id }} </td>
            <td> {{ project.user }}</td>
            <td> {{ project.name }}</td>
            <td> {{ project.state }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %} 

templates/economy.html
{% extends "base.html" %} {% block content %}
<div class="w3-card-4">
  <header class="w3-container w3-small w3-blue">
    <h4 class="w3-center">Economy</h4>
  </header>

  <div class="w3-container w3-card">
    {% for industry in industries %}
    <table class="w3-table-all w3-small">
      <thead>
        <tr class="w3-light-blue">
          <th>Industry</th>
          <th>Commodity</th>
          <th class="w3-right-align">Supply (=sales stock)</th>
          <th class="w3-right-align">Money (=money stock)</th>
          <th class="w3-right-align">Output Scale</th>
          <th class="w3-right-align">Initial Capital</th>
          <th class="w3-right-align">Current Capital</th>
          <th class="w3-right-align">Profit</th>
        </tr>
      </thead>
      <tbody>
        <td>{{industry.link|safe}}</td>
        <td><a href="/commodities/{{industry.commodity.id}}/">{{ industry.commodity }}</a></td>
        <td class="w3-right-align"> {{industry.sales_stock.size |floatformat:0}} </td>
        <td class="w3-right-align"> {{industry.money_stock.size |floatformat:0}} </td>
        <td class="w3-right-align"> {{industry.output_scale |floatformat:0}} </td>
        <td class="w3-right-align"> {{industry.initial_capital|floatformat:0}} </td>
        <td class="w3-right-align"> {{industry.current_capital |floatformat:0}} </td>
        <td class="w3-right-align"> {{industry.profit |floatformat:0}} </td>

      </tbody>
    </table>
    <div class="w3-card">
      <table class="w3-table-all w3-small " style="width:90%; margin:auto">
        <thead>
          <tr class="w3-light-grey">
            <th>Stock Details</th>
            <th>Commodity</th>
            <th>Usage</th>
            <th class="w3-right-align"> Size</th>
            <th class="w3-right-align"> Requirement</th>
            <th class="w3-right-align"> Value</th>
            <th class="w3-right-align"> Price</th>
            <th class="w3-right-align"> Demand</th>
          </tr>
        </thead>
        <tbody>
          {% for stock in industry.stocks.all %}
          <tr>
            <td> {{stock.link|safe}}</td>
            <td> {{stock.commodity.link|safe}}</td>
            <td> {{stock.usage_type}}</td>
            <td class="w3-right-align"> {{stock.size|floatformat:0}}</td>
            <td class="w3-right-align"> {{stock.requirement|floatformat:0}}</td>
            <td class="w3-right-align"> {{stock.value|floatformat:0}}</td>
            <td class="w3-right-align"> {{stock.price|floatformat:0}}</td>
            <td class="w3-right-align"> {{stock.demand|floatformat:0}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endfor %}
  </div>

  {% for socialclass in social_classes %}
  <table class="w3-table-all w3-small">
    <thead>
      <tr class="w3-light-blue">
        <th>Social Class</th>
        <th>Commodity</th>
        <th class="w3-right-align">Population</th>
        <th class="w3-right-align">Consumption Ratio</th>
      </tr>
    </thead>
    <tbody>
      <td>{{socialclass.link |safe}}</td>
      <td>{{ socialclass.commodity.link|safe }}</td>
      <td class="w3-right-align"> {{socialclass.population|floatformat:0}} </td>
      <td class="w3-right-align"> {{socialclass.consumption_ratio|floatformat:0}} </td>

    </tbody>
  </table>
  <div class="w3-card" style="width:90%; margin:auto">
  <table class="w3-table-all w3-small">
    <thead>
      <tr class="w3-light-grey">
        <th> Stock Details</th>
        <th> Commodity</th>
        <th> Usage</th>
        <th  class="w3-right-align"> Size</th>
        <th class="w3-right-align"> Requirement</th>
        <th class="w3-right-align"> Value</th>
        <th class="w3-right-align"> Price</th>
        <th class="w3-right-align"> Demand</th>
      </tr>
    </thead>
    <tbody>
      {% for stock in socialclass.stocks.all %}

      <tr>
        <td> {{stock.link|safe }}</td>
        <td> {{stock.commodity.link |safe}}</td>
        <td> {{stock.usage_type}}</td>
        <td  class="w3-right-align"> {{stock.size|floatformat:0}}</td>
        <td  class="w3-right-align"> {{stock.requirement|floatformat:0}}</td>
        <td  class="w3-right-align"> {{stock.value|floatformat:0}}</td>
        <td  class="w3-right-align"> {{stock.price|floatformat:0}}</td>
        <td class="w3-right-align"> {{stock.demand|floatformat:0}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

  {% endfor %}
</div>

</div>
{% endblock %}

templates/home.html
{% extends "base.html" %} {% block content %}
<h2> welcome to capitalism</h2>

{% endblock %} 

templates/industries.html
{% extends "base.html" %} {% block content %}
<h3 class="w3-center">Industries in project {{ simulation }} </h3>
<table id="commodities" class="w3-table-all w3-card w3-small">
    <thead>
        <tr>
            {% if user.is_staff %}
            <th class="w3-right-align">User</th>
            {% endif %}

            <th>Name</th>
            <th>Commodity</th>
            <th class="w3-right-align">Scale</th>
            <th class="w3-right-align">Growth rate</th>
            <th class="w3-right-align">Money</th>
            <th class="w3-right-align">Initial capital</th>
            <th class="w3-right-align">Work in progress</th>
            <th class="w3-right-align">Capital</th>
            <th class="w3-right-align">Profit</th>
            <th class="w3-right-align">Profit rate</th>
        </tr>
    </thead>
    <tbody>
        {% for industry in industry_list %}
        <tr>
            {% if user.is_staff %}
            <td>{{ industry.simulation.user }}</td>
            {% endif %}

            <td><a href ="{{industry.id}}"> {{ industry.name }} 

                {% if user.is_staff %}
                ({{ industry.id }})
                {% endif %}
    
            </a></td>
            <td><a href ="/commodities/{{industry.commodity.id}}"> {{ industry.commodity.name }} </a></td>
            <td class="w3-right-align">{{ industry.output_scale|floatformat:0 }}</td>
            <td class="w3-right-align">{{ industry.output_growth_rate }}</td>
            <td class="w3-right-align">{{ industry.money_stock.size|floatformat:0}}</td>
            <td class="w3-right-align">{{ industry.initial_capital|floatformat:0 }}</td>
            <td class="w3-right-align">{{ industry.work_in_progress|floatformat:0 }}</td>
            <td class="w3-right-align">{{ industry.current_capital|floatformat:0 }}</td>
            <td class="w3-right-align">{{ industry.profit|floatformat:0 }}</td>
            <td class="w3-right-align">{{ industry.profit_rate }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %} 

templates/industry_detail.html
{% extends "base.html" %} {% block content %}
<div class="w3-card-4" style="width:50%; margin:auto">
  <header class="w3-container w3-blue">
    <h2 class="w3-center"> {{ industry.name }}</h2>
  </header>

  <div class="w3-container  w3-card">
    <table id="industry" class="w3-table-all w3-small">
      <thead>
  
      </thead>
      <tbody>
          <tr> <td> Commodity  </td><td><a href="/commodities/{{industry.commodity.id}}/">{{ industry.commodity  }}</a></td><tr>
          <tr> <td> Output scale  </td><td>{{ industry.output_scale  }}</td><tr>
          <tr> <td> Growth rate  </td><td>{{ industry.output_growth_rate  }}</td><tr>
          <tr> <td> Work in progress </td><td>{{ industry.work_in_progress }}</td><tr>
          <tr> <td> Initial capital </td><td>{{ industry.initial_capital }}</td><tr>
          <tr> <td> Current capital </td><td>{{ industry.current_capital }}</td><tr>
          <tr> <td> Profit </td><td>{{ industry.profit }}</td><tr>
          <tr> <td> Profit rate </td><td>{{ industry.profit_rate }}</td><tr>
      </tbody>
    </table>
  </div>


</div>
{% endblock %}

templates/owner_detail.html
{% extends "base.html" %} {% block content %}
<div class="w3-card-4" style="width:50%; margin:auto">
  <header class="w3-container w3-blue">
    <h2 class="w3-center"> {{ owner.name }}</h2>
  </header>

  <div class="w3-container  w3-card">
    <table id="owner" class="w3-table-all w3-small">
      <thead>
  
      </thead>
      <tbody>
          <tr> <td> Commodity  </td><td><a href="/commodities/{{industry.commodity.id}}/">{{ owner.commodity  }}</a></td><tr>
      </tbody>
    </table>
  </div>


</div>
{% endblock %}

templates/user-dashboard.html
{% extends "base.html" %} {% block content %}

<div class="w3-container" style="width:80%">
    <div class="w3-medium">
        <h4>Project Management</h4>
        <p>
        <div class="w3-btn w3-block w3-round w3-red ">
            Your Simulations
        </div>
        </p>
        <table id="simulation" class="display compact w3-small" style="width:80%">
            <tbody>
                {% for simulation in simulation_list %}
                <tr>
                    <td> {{ simulation.project_number }} ({{ simulation.project_description }})</td>
                    <td> {{ simulation.name }}</td>
                    <td> {{ simulation.periods_per_year }}</td>
                    <td> <a href="/select-simulation/{{ simulation.pk }}"
                            class="w3-button w3-round-large w3-green ">Switch</a>
                    </td>
                    <td><a href="/delete-simulation/{{ simulation.pk }} "
                            class="w3-button w3-round-large w3-red ">Delete</a>
                    </td>
                    <td>
                        <a href="/restart-simulation/{{ simulation.pk}}"
                            class="w3-button w3-round-large w3-orange ">Restart</a>
                    </td>
                    <td> <button class="w3-button w3-grey w3-round-large ">Download</button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <p>
        <div class="w3-btn w3-block w3-round w3-green ">
            Available Projects
        </div>
        <table id="projects" class="display compact w3-small" style="width:80%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Periods</th>
                    <th>Select</th>
                </tr>
            </thead>
            <tbody>
                {% for simulation in project_list %}
                <tr>
                    <td> {{ simulation.name }}</td>
                    <td> {{ simulation.periods_per_year }}</td>
                    <td> <a href="/create-simulation/{{ simulation.pk }}"
                            class="w3-button w3-round-large w3-green ">Create new simulation</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </p>

    </div>
    </p>
</div>
</p>

{% endblock %} {% block extra_js %}
<script>
    $(document).ready(function () {
        $('#simulation').DataTable({
            "paging ": false,
            "searching ": false,
            "info ": false
        });
    });
</script>
{% endblock %}